// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiSEx3zlA9aPUkSdNM9LknKKTa87f8gYM',
    appId: '1:811395658930:web:fe7e80dc52af53552205ab',
    messagingSenderId: '811395658930',
    projectId: 'flasholator-cf84b',
    authDomain: 'flasholator-cf84b.firebaseapp.com',
    storageBucket: 'flasholator-cf84b.firebasestorage.app',
    measurementId: 'G-B7P7WHHLLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM9EIeNYTuOz25zTzMS-ZmYBAhvh81APQ',
    appId: '1:811395658930:android:8d622c45f5bf92722205ab',
    messagingSenderId: '811395658930',
    projectId: 'flasholator-cf84b',
    storageBucket: 'flasholator-cf84b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZFDtN6h66Z_A7H2y5va8dHlTu9MyLeAs',
    appId: '1:811395658930:ios:34553c17f5b96ed82205ab',
    messagingSenderId: '811395658930',
    projectId: 'flasholator-cf84b',
    storageBucket: 'flasholator-cf84b.firebasestorage.app',
    iosBundleId: 'com.felinx18.flasholator',
  );

}