name: Build and Deploy AAB on Playstore

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

env:
  BUILD_NUMBER: 10
  BUILD_NAME: 0.4.0
  KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
  STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5'
        channel: 'stable'
    
    - name: Get dependencies
      run: flutter pub get

    - name: Decode Keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks

    - name: Build APK
      run: |
        flutter build apk --release --split-per-abi \
          --build-number=${{ env.BUILD_NUMBER }} \
          --build-name=${{ env.BUILD_NAME }}

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/flutter-apk/*.apk"
        tag: v${{ env.BUILD_NAME }}
        name: Release v${{ env.BUILD_NAME }}
        body: New release for version ${{ env.BUILD_NAME }}
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build AAB
      run: |
        flutter build appbundle --release \
          --build-number=${{ env.BUILD_NUMBER }} \
          --build-name=${{ env.BUILD_NAME }}
        
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/bundle/release/app-release.aab"
        tag: v${{ env.BUILD_NAME }}
        name: Release v${{ env.BUILD_NAME }}
        body: New release for version ${{ env.BUILD_NAME }}
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Deploy to Google Play
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        packageName: com.felinx18.flasholator
        releaseFiles: build/app/outputs/bundle/release/app-release.aab
        track: production
        status: completed
